export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
    genre_ids: [35, 10767],
    id: 63770,
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Late Show with Stephen Colbert",
    overview:
      "Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater. Stephen Colbert, Chris Licht, Tom Purcell, and Jon Stewart are executive producers. Barry Julien and Denise Rehrig serve as co-executive producers.must watch",
    popularity: 4109.785,
    poster_path: "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
    first_air_date: "2015-09-08",
    name: "The Late Show with Stephen Colbert",
    vote_average: 5.6,
    vote_count: 285,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    backdrop_path: "/2Ib8kvWa9gGhJrAfGlhIvbmtbWn.jpg",
    id: 32415,
    name: "Conan",
    original_name: "Conan",
    overview: "A late night television talk show hosted by  Conan O'Brien.",
    poster_path: "/oQxrvUhP3ycwnlxIrIMQ9Z3kleq.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10767, 35, 10763],
    popularity: 1567.881,
    first_air_date: "2010-11-08",
    vote_average: 7,
    vote_count: 228,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/uganUhifpqzzAunI0PETnutlmR.jpg",
    id: 8621,
    name: "Late Night with Jimmy Fallon",
    original_name: "Late Night with Jimmy Fallon",
    overview:
      "Late Night with Jimmy Fallon is an American late-night talk show airing weeknights at 12:35 am Eastern/11:35 pm Central on NBC in the United States. The hour-long show premiered on March 2, 2009, and is hosted by actor, comedian and performer Jimmy Fallon, an alumnus of Saturday Night Live. Hip hop/neo soul band The Roots serve as the show's house band, and Steve Higgins is the show's announcer.\n\nThe third incarnation of the Late Night franchise originated by David Letterman, the program originates from NBC Studio 6B in the GE Building at 30 Rockefeller Center in New York City. The show typically opens with a brief monologue from Fallon, followed by a comedy \"desk piece,\" as well as prerecorded segments and audience competitions. The next segment is devoted to a celebrity interview, with guests ranging from actors and musicians to media personalities and political figures. The show then closes with either a musical or comedy performance. The show frequently employs digital media into its comedy, which has become crucial to its success. Fallon has been appointed to become the next host of The Tonight Show, where he will succeed the current host Jay Leno at the conclusion of the 2014 Winter Olympics, with fellow SNL alum Seth Meyers slated to replace Fallon.",
    poster_path: "/l8WzbOr7vg3WDlB3hoy32wZDxwj.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10767],
    popularity: 262.9,
    first_air_date: "2009-03-02",
    vote_average: 6,
    vote_count: 93,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/sOBK7XRjdEmcgeMTMzX0A7ed0S.jpg",
    id: 75804,
    name: "Our Cartoon President",
    original_name: "Our Cartoon President",
    overview:
      "A hilarious look into the Trump presidency, animation style. Starring two-dimensional avatars of Donald Trump and his merry band of insiders and family members, this cutting-edge comedy presents the truish adventures of Trump, his confidants and bon vivants through the eyes of an imaginary documentary crew.",
    poster_path: "/pVmH4R0d34UHH3n9ODWbPC3ALn7.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [16, 35],
    popularity: 36.879,
    first_air_date: "2018-02-11",
    vote_average: 5.4,
    vote_count: 34,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/6zHVJh9QvrzmqCozDB7JC5tYaa1.jpg",
    id: 7967,
    name: "The Rachel Maddow Show",
    original_name: "The Rachel Maddow Show",
    overview:
      "The Rachel Maddow Show is a daily news and opinion television program that airs on MSNBC, running in the 9:00 pm ET timeslot. It is hosted by Rachel Maddow, who gained popularity with her frequent appearances as a liberal pundit on various MSNBC programs. It is based on her former radio show of the same name. The show debuted on September 8, 2008.",
    poster_path: "/xAJRCha3Q3iY27IrZg4sycsJ8Kt.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10763, 10767],
    popularity: 562.247,
    first_air_date: "2008-09-08",
    vote_average: 6.1,
    vote_count: 30,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/ge4mIJjh3kZ1oXGblRoVB5h6xPo.jpg",
    id: 242965,
    name: "After Midnight",
    original_name: "After Midnight",
    overview:
      "Celebrated comedian Taylor Tomlinson hosts the smartest show on television about the dumbest things on the internet alongside a panel of guests from the worlds of entertainment, comedy, music and beyond.",
    poster_path: "/7O67hHXEaiW30UQdunBqlyPsfGh.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [35, 10767],
    popularity: 94.009,
    first_air_date: "2024-01-17",
    vote_average: 6.7,
    vote_count: 13,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/1LdoySO2wr2AtJUvxIoMEkCySZC.jpg",
    id: 34860,
    name: "Ninja Boy Rantaro",
    original_name: "忍たま乱太郎",
    overview:
      'Rantarō, Shinbei and Kirimaru are ninja  apprentices in the Ninja Gakuen, where first grade ones are called  "Nintamas". They must learn  everything a ninja must know, but as for our heroes, money, food or  playing are more interesting. The series show the everyday adventures of  our heroes.',
    poster_path: "/xdnt8Dx5Z8Ad78GfqSSsk9kv4tB.jpg",
    media_type: "tv",
    adult: false,
    original_language: "ja",
    genre_ids: [35, 10759, 10762, 16, 10751],
    popularity: 2104.051,
    first_air_date: "1993-04-10",
    vote_average: 6.2,
    vote_count: 18,
    origin_country: ["JP"],
  },
  {
    backdrop_path: "/oSv4WdBFcQLgVjGsRPmU7WcYFxC.jpg",
    id: 115992,
    name: "The Damage Report with John Iadarola",
    original_name: "The Damage Report with John Iadarola",
    overview:
      "Welcome to The Damage Report with John Iadarola, your daily breakdown of the true threats and challenges facing our country and our world. John Iadarola hosts an unflinching, no-holds-barred look at the damage the Trump administration is causing.",
    poster_path: "/ckJWPg2f9F0oJSvjInHi4Mk6Lrz.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10763],
    popularity: 72.951,
    first_air_date: "2018-11-28",
    vote_average: 7.5,
    vote_count: 2,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/lsnicyZfStZe1EdDzRJf7mE98IN.jpg",
    id: 17640,
    name: "Kate Garraway's Life Stories",
    original_name: "Kate Garraway's Life Stories",
    overview:
      "Celebrities open up to Kate Garraway in intimate and moving interviews.",
    poster_path: "/hUJkFuea7tzRAsFaX3qHZ5A5EHx.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10767],
    popularity: 68.051,
    first_air_date: "2009-02-22",
    vote_average: 5.9,
    vote_count: 9,
    origin_country: ["GB"],
  },
  {
    backdrop_path: "/ttN99rRQUYHD7azOl8EVmuftAGZ.jpg",
    id: 31750,
    name: "The War",
    original_name: "The War",
    overview:
      "The story of the Second World War through the personal accounts of a handful of men and women from four American towns. The war touched the lives of every family on every street in every town in America and demonstrated that in extraordinary times, there are no ordinary lives.",
    poster_path: "/s2pJDvs6LZdijaiWCdSuLRkDryV.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [99, 10768, 80],
    popularity: 14.618,
    first_air_date: "2008-03-05",
    vote_average: 8.1,
    vote_count: 55,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/unzZzmBD8bfXR7kdmGcjW0ixgQ0.jpg",
    id: 17535,
    name: "The Tonight Show with Conan O'Brien",
    original_name: "The Tonight Show with Conan O'Brien",
    overview: "",
    poster_path: "/hkDDxwhBKqrziSVHZknZFomTslq.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10767, 35],
    popularity: 78.494,
    first_air_date: "2009-06-01",
    vote_average: 7,
    vote_count: 77,
    origin_country: ["US"],
  },
];
